//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainChoice) DeepCopyInto(out *DomainChoice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainChoice.
func (in *DomainChoice) DeepCopy() *DomainChoice {
	if in == nil {
		return nil
	}
	out := new(DomainChoice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Horizon) DeepCopyInto(out *Horizon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Horizon.
func (in *Horizon) DeepCopy() *Horizon {
	if in == nil {
		return nil
	}
	out := new(Horizon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Horizon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizonList) DeepCopyInto(out *HorizonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Horizon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizonList.
func (in *HorizonList) DeepCopy() *HorizonList {
	if in == nil {
		return nil
	}
	out := new(HorizonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorizonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizonSpec) DeepCopyInto(out *HorizonSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	out.Image = in.Image
	in.Cache.DeepCopyInto(&out.Cache)
	out.SecretKeyRef = in.SecretKeyRef
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebSSO != nil {
		in, out := &in.WebSSO, &out.WebSSO
		*out = new(WebSSOSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiDomain != nil {
		in, out := &in.MultiDomain, &out.MultiDomain
		*out = new(MultiDomainSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizonSpec.
func (in *HorizonSpec) DeepCopy() *HorizonSpec {
	if in == nil {
		return nil
	}
	out := new(HorizonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizonStatus) DeepCopyInto(out *HorizonStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizonStatus.
func (in *HorizonStatus) DeepCopy() *HorizonStatus {
	if in == nil {
		return nil
	}
	out := new(HorizonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiDomainSpec) DeepCopyInto(out *MultiDomainSpec) {
	*out = *in
	if in.DomainChoices != nil {
		in, out := &in.DomainChoices, &out.DomainChoices
		*out = make([]DomainChoice, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiDomainSpec.
func (in *MultiDomainSpec) DeepCopy() *MultiDomainSpec {
	if in == nil {
		return nil
	}
	out := new(MultiDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSSOChoice) DeepCopyInto(out *WebSSOChoice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSSOChoice.
func (in *WebSSOChoice) DeepCopy() *WebSSOChoice {
	if in == nil {
		return nil
	}
	out := new(WebSSOChoice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSSOIDPTarget) DeepCopyInto(out *WebSSOIDPTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSSOIDPTarget.
func (in *WebSSOIDPTarget) DeepCopy() *WebSSOIDPTarget {
	if in == nil {
		return nil
	}
	out := new(WebSSOIDPTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSSOSpec) DeepCopyInto(out *WebSSOSpec) {
	*out = *in
	if in.Choices != nil {
		in, out := &in.Choices, &out.Choices
		*out = make([]WebSSOChoice, len(*in))
		copy(*out, *in)
	}
	if in.IDPMapping != nil {
		in, out := &in.IDPMapping, &out.IDPMapping
		*out = make(map[string]WebSSOIDPTarget, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSSOSpec.
func (in *WebSSOSpec) DeepCopy() *WebSSOSpec {
	if in == nil {
		return nil
	}
	out := new(WebSSOSpec)
	in.DeepCopyInto(out)
	return out
}
