#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0
"""Generator for the invalid-CR Chainsaw fixtures.

Single source of truth for the minimal valid Keystone CR scaffold used by every
``invalid-cr`` rejection test. Each fixture below mutates exactly one
field of the canonical scaffold so the surrounding CR passes schema validation
for every rule OTHER than the one under test, ensuring the admission error is
attributable to that single field.

The reviewer concern this generator addresses (sourcery-ai review #1):
without a single source of truth the 11 fixtures could drift out of sync with
each other and with KeystoneSpec over time. This script enforces a single
canonical scaffold; per-fixture overrides change only what is necessary to
trigger the rejection path under test.

Usage:

    # Regenerate all fixtures from this single source of truth.
    python3 _generate.py

    # CI-friendly drift check: exit non-zero if any on-disk fixture diverges
    # from the regenerated content.
    python3 _generate.py --check

The fixtures (``00-invalid-cron.yaml``, ``01-duplicate-plugins.yaml``)
are intentionally NOT regenerated by this script: they predate and
their git history is preserved verbatim.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

# matches every two-digit-prefixed fixture in this directory. Used by
# the orphan-detection sweep in main() so a fixture removed from FIXTURES but
# left on disk is reported as drift, closing the gap that FC1/W-002 (review #2
# from berendt) flagged. Broadened from the original 02-19 bound (review #3) so that any future ID-space expansion stays covered automatically;
# the pre-existing fixtures are exempted via _PRE_CC0094_FIXTURES so
# the sweep does not flag them as orphans.
_FIXTURE_FILENAME_PATTERN = re.compile(r"^[0-9]{2}-.+\.yaml$")

# filenames that match _FIXTURE_FILENAME_PATTERN but predate
# and are intentionally NOT regenerated by this script. The orphan sweep in
# main() must skip these so it does not delete or flag them as drift.
_PRE_CC0094_FIXTURES = frozenset(
    {
        "00-invalid-cron.yaml",
        "01-duplicate-plugins.yaml",
    }
)

LICENSE_HEADER = """\
# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

"""

# Canonical valid Keystone CR scaffold. Any future required field on
# KeystoneSpec must be added below AND verified against every fixture.
DATABASE_HOST_ONLY = """\
    host: db.example.com
    port: 3306
    database: keystone
    secretRef:
      name: keystone-db
"""

DATABASE_BOTH_MODES = """\
    clusterRef:
      name: openstack-db
    host: db.example.com
    port: 3306
    database: keystone
    secretRef:
      name: keystone-db
"""

CACHE_SERVERS_ONLY = """\
    backend: dogpile.cache.pymemcache
    servers:
    - "mc:11211"
"""

CACHE_BOTH_MODES = """\
    clusterRef:
      name: openstack-memcached
    backend: dogpile.cache.pymemcache
    servers:
    - "mc:11211"
"""

BOOTSTRAP = """\
  bootstrap:
    adminUser: admin
    adminPasswordSecretRef:
      name: keystone-admin
    region: RegionOne
"""


@dataclass(frozen=True)
class Fixture:
    """One invalid-CR fixture: filename + per-fixture overrides."""

    filename: str
    name: str
    comment: str
    replicas: int = 3
    database: str = DATABASE_HOST_ONLY
    cache: str = CACHE_SERVERS_ONLY
    fernet_max_active_keys: int = 3
    credential_keys: str | None = None
    trailing: str | None = None


def render(fixture: Fixture) -> str:
    """Render a single invalid-CR fixture from the canonical scaffold."""
    parts: list[str] = [
        LICENSE_HEADER,
        fixture.comment.rstrip() + "\n",
        "apiVersion: keystone.openstack.c5c3.io/v1alpha1\n",
        "kind: Keystone\n",
        "metadata:\n",
        f"  name: {fixture.name}\n",
        "spec:\n",
        f"  replicas: {fixture.replicas}\n",
        "  image:\n",
        "    repository: ghcr.io/c5c3/keystone\n",
        '    tag: "2025.2"\n',
        "  database:\n",
        fixture.database,
        "  cache:\n",
        fixture.cache,
        "  fernet:\n",
        '    rotationSchedule: "0 0 * * 0"\n',
        f"    maxActiveKeys: {fixture.fernet_max_active_keys}\n",
    ]
    if fixture.credential_keys is not None:
        parts.append(fixture.credential_keys)
    parts.append(BOOTSTRAP)
    if fixture.trailing is not None:
        parts.append(fixture.trailing)
    return "".join(parts)


FIXTURES: list[Fixture] = [
    Fixture(
        filename="02-database-both-modes.yaml",
        name="invalid-database-both-modes",
        database=DATABASE_BOTH_MODES,
        comment="""\
# Keystone CR that sets BOTH spec.database.clusterRef AND
# spec.database.host. Mutual-exclusivity is enforced by the CEL XValidation
# rule on the shared commonv1.DatabaseSpec (types.go) and by defense-in-depth
# in the validating webhook (keystone_webhook.go). Admission must reject
# this CR with an $error referencing spec.database and the message
# "exactly one of clusterRef or host must be set".""",
    ),
    Fixture(
        filename="03-cache-both-modes.yaml",
        name="invalid-cache-both-modes",
        cache=CACHE_BOTH_MODES,
        comment="""\
# Keystone CR that sets BOTH spec.cache.clusterRef AND
# a non-empty spec.cache.servers list. Mutual-exclusivity is enforced by
# the CEL XValidation rule on the shared commonv1.CacheSpec (types.go) and
# by the validating webhook (keystone_webhook.go). Admission must reject
# this CR with an $error referencing spec.cache and the message
# "exactly one of clusterRef or servers must be set". A non-empty servers
# list is required for the CEL guard `size(self.servers) > 0` to fire.""",
    ),
    Fixture(
        filename="04-autoscaling-no-target.yaml",
        name="invalid-autoscaling-no-target",
        trailing="""\
  autoscaling:
    maxReplicas: 10
""",
        comment="""\
# Keystone CR with spec.autoscaling configured but
# neither targetCPUUtilization nor targetMemoryUtilization set. The
# requirement is enforced by the CEL XValidation rule on AutoscalingSpec
# (keystone_types.go) and by the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing spec.autoscaling
# and the message "at least one of targetCPUUtilization or
# targetMemoryUtilization must be set".""",
    ),
    Fixture(
        filename="05-policy-overrides-no-source.yaml",
        name="invalid-policy-overrides-no-source",
        trailing="  policyOverrides: {}\n",
        comment="""\
# Keystone CR with spec.policyOverrides set to an empty
# object — neither rules nor configMapRef populated. The constraint is
# enforced by the CEL XValidation rule on KeystoneSpec.PolicyOverrides
# (keystone_types.go) and by the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing
# spec.policyOverrides and the message "at least one of rules or
# configMapRef must be set".""",
    ),
    Fixture(
        filename="06-policy-overrides-empty-rule-key.yaml",
        name="invalid-policy-overrides-empty-rule-key",
        trailing="""\
  policyOverrides:
    rules:
      '': "role:admin"
""",
        comment="""\
# Keystone CR with spec.policyOverrides.rules containing
# an empty-string map key. Forbidden by the CEL XValidation rule on
# commonv1.PolicySpec (`self.rules.all(k, size(k) > 0)` in types.go) and by
# policy.ValidatePolicyRules in the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing the parent
# fieldPath spec.policyOverrides and the message "policy rule name must
# not be empty". The chainsaw assertion intentionally matches the parent
# path (spec.policyOverrides) — not the deeper spec.policyOverrides.rules
# — because CEL XValidation runs before the validating webhook in the
# admission pipeline and emits the error at the field where the rule is
# declared (here: policyOverrides). The validating webhook's deeper-path
# message is unreachable when the CEL layer rejects first. The empty key
# is quoted ('') so the YAML parser preserves it.""",
    ),
    Fixture(
        filename="07-networkpolicy-empty-ingress.yaml",
        name="invalid-networkpolicy-empty-ingress",
        trailing="""\
  networkPolicy:
    ingress: []
""",
        comment="""\
# Keystone CR with spec.networkPolicy set but
# spec.networkPolicy.ingress as an empty array. The constraint is enforced
# by the CEL XValidation rule on NetworkPolicySpec (keystone_types.go) and
# by the validating webhook (keystone_webhook.go). Admission must reject
# this CR with an $error referencing the parent fieldPath spec.networkPolicy
# and the message "at least one ingress source must be specified". The
# chainsaw assertion intentionally matches the parent path
# (spec.networkPolicy) — not the deeper spec.networkPolicy.ingress —
# because the CEL XValidation rule is declared on the NetworkPolicySpec
# type at the field used as spec.networkPolicy, so the apiserver emits the
# error at that parent path. The validating webhook's deeper-path message
# is unreachable when the CEL layer rejects first.""",
    ),
    Fixture(
        filename="09-replicas-negative.yaml",
        name="invalid-replicas-negative",
        replicas=-1,
        comment="""\
# Keystone CR with spec.replicas: -1. The
# +kubebuilder:validation:Minimum=1 marker on KeystoneSpec.Replicas
# (keystone_types.go) is a structural CRD check that runs before any
# defaulting path could coerce a negative value. The defaulting webhook
# only normalizes Replicas == 0 (keystone_webhook.go), so -1 reaches the
# Minimum=1 schema layer. Admission must reject this CR with an $error
# referencing the substring "replicas".""",
    ),
    Fixture(
        filename="10-hpa-min-greater-than-max.yaml",
        name="invalid-hpa-min-greater-than-max",
        trailing="""\
  autoscaling:
    minReplicas: 10
    maxReplicas: 5
    targetCPUUtilization: 80
""",
        comment="""\
# Keystone CR with spec.autoscaling.minReplicas greater
# than spec.autoscaling.maxReplicas. The validating webhook
# (keystone_webhook.go) rejects the cross-field combination because an HPA
# rendered with min > max would itself be rejected by the API server.
# Admission must reject this CR with an $error referencing
# spec.autoscaling.minReplicas and the message "must not exceed
# maxReplicas". A targetCPUUtilization is set so the rejection is
# attributable solely to the min/max ordering, not the no-target rule.""",
    ),
    Fixture(
        filename="11-fernet-maxactivekeys-below-minimum.yaml",
        name="invalid-fernet-maxactivekeys-below-minimum",
        fernet_max_active_keys=2,
        comment="""\
# Keystone CR with spec.fernet.maxActiveKeys: 2 — below
# the documented minimum. Enforced by the +kubebuilder:validation:Minimum=3
# marker on FernetSpec.MaxActiveKeys (keystone_types.go) and by
# defense-in-depth in the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing the substring
# "maxActiveKeys". Either layer's message ("should be greater than or
# equal to 3" from CRD schema, "maxActiveKeys must be at least 3" from
# webhook) satisfies the assertion — see plan on layer-order
# tolerance.""",
    ),
    Fixture(
        filename="12-credentialkeys-maxactivekeys-below-minimum.yaml",
        name="invalid-credentialkeys-maxactivekeys-below-minimum",
        credential_keys="""\
  credentialKeys:
    rotationSchedule: "0 0 * * 0"
    maxActiveKeys: 2
""",
        comment="""\
# Keystone CR with spec.credentialKeys.maxActiveKeys: 2 —
# below the documented minimum. Enforced by the
# +kubebuilder:validation:Minimum=3 marker on
# CredentialKeysSpec.MaxActiveKeys (keystone_types.go) and by
# defense-in-depth in the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing the substring
# "maxActiveKeys". Either layer's message satisfies the assertion — see
# plan on layer-order tolerance.""",
    ),
    Fixture(
        filename="13-policy-overrides-empty-rule-value.yaml",
        name="invalid-policy-overrides-empty-rule-value",
        trailing="""\
  policyOverrides:
    rules:
      "identity:get_user": ""
""",
        comment="""\
# Keystone CR with spec.policyOverrides.rules containing a
# rule whose VALUE is the empty string. This closes the validation gap the
# 2026-06 audit reported (issue #479): empty rule values previously passed
# admission and reached oslo.policy. Forbidden by the CEL XValidation rule on
# commonv1.PolicySpec (`self.rules.all(k, self.rules[k] != '')` in types.go)
# and by policy.ValidatePolicyRules in the validating webhook
# (keystone_webhook.go). Admission must reject this CR with an $error
# referencing the parent fieldPath spec.policyOverrides and the message
# "policy rule value must not be empty". As with the empty-key sibling
# (06-policy-overrides-empty-rule-key.yaml), the chainsaw assertion matches the parent path
# (spec.policyOverrides) because the CEL XValidation, embedded on the
# policyOverrides field via its PolicySpec type, runs before the validating
# webhook and emits the error at that field. The key is quoted to keep its
# embedded colon unambiguous to the YAML parser.""",
    ),
]


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    here = Path(__file__).resolve().parent
    drift: list[str] = []
    for fixture in FIXTURES:
        rendered = render(fixture)
        target = here / fixture.filename
        # (I-001): pin encoding=utf-8 so the em-dash characters in the
        # rendered comments round-trip deterministically on runners with a
        # non-UTF-8 locale; otherwise locale.getpreferredencoding() could
        # mis-decode the on-disk file and falsely flag every fixture as drifted.
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            continue
        if check_only:
            drift.append(fixture.filename)
        else:
            target.write_text(rendered, encoding="utf-8")
            print(f"wrote {fixture.filename}")
    # (W-002): orphan sweep. Without this, removing a Fixture entry
    # without `git rm`'ing the YAML leaves dead code on disk that --check
    # cannot see (it only iterates FIXTURES). Report orphans as drift in
    # check mode; delete them otherwise so the on-disk set matches FIXTURES.
    # Files in _PRE_CC0094_FIXTURES are exempted because they predate
    # and are not generated here.
    expected = {f.filename for f in FIXTURES} | _PRE_CC0094_FIXTURES
    for path in sorted(here.iterdir()):
        if (
            path.is_file()
            and _FIXTURE_FILENAME_PATTERN.match(path.name)
            and path.name not in expected
        ):
            if check_only:
                drift.append(f"{path.name} (orphan: not in FIXTURES)")
            else:
                path.unlink()
                print(f"removed orphan {path.name}")
    if check_only and drift:
        print(
            "drift detected — re-run `python3 _generate.py` to refresh:",
            file=sys.stderr,
        )
        for filename in drift:
            print(f"  {filename}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
