#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0
"""Generator for the invalid-CR Chainsaw fixtures.

Single source of truth for the minimal valid Keystone CR scaffold used by every
``invalid-cr`` rejection test. Each fixture below mutates exactly one
field of the canonical scaffold so the surrounding CR passes schema validation
for every rule OTHER than the one under test, ensuring the admission error is
attributable to that single field.

Two fixture categories share this scaffold:

* Create-rejection fixtures are each applied once and rejected at admission by
  a CEL XValidation or ``webhook.validate()`` rule.
* Update-rejection fixtures (#466) share the name ``immutable-fields``:
  ``13-immutable-base`` is the valid base CR applied first, and the ``14``-
  ``17`` variants are applied as UPDATEs of that base so the CRD CEL transition
  rules (``self == oldSelf``, evaluated only on UPDATE) reject the field change.

The reviewer concern this generator addresses (sourcery-ai review #1):
without a single source of truth the fixtures could drift out of sync with
each other and with KeystoneSpec over time. This script enforces a single
canonical scaffold; per-fixture overrides change only what is necessary to
trigger the rejection path under test.

Usage:

    # Regenerate all fixtures from this single source of truth.
    python3 _generate.py

    # CI-friendly drift check: exit non-zero if any on-disk fixture diverges
    # from the regenerated content.
    python3 _generate.py --check

The fixtures (``00-invalid-cron.yaml``, ``01-duplicate-plugins.yaml``)
are intentionally NOT regenerated by this script: they predate and
their git history is preserved verbatim.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

# matches every two-digit-prefixed fixture in this directory. Used by
# the orphan-detection sweep in main() so a fixture removed from FIXTURES but
# left on disk is reported as drift, closing the gap that FC1/W-002 (review #2
# from berendt) flagged. Broadened from the original 02-19 bound (review #3) so that any future ID-space expansion stays covered automatically;
# the pre-existing fixtures are exempted via _PRE_CC0094_FIXTURES so
# the sweep does not flag them as orphans.
_FIXTURE_FILENAME_PATTERN = re.compile(r"^[0-9]{2}-.+\.yaml$")

# filenames that match _FIXTURE_FILENAME_PATTERN but predate
# and are intentionally NOT regenerated by this script. The orphan sweep in
# main() must skip these so it does not delete or flag them as drift.
_PRE_CC0094_FIXTURES = frozenset(
    {
        "00-invalid-cron.yaml",
        "01-duplicate-plugins.yaml",
    }
)

LICENSE_HEADER = """\
# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

"""

# Canonical valid Keystone CR scaffold. Any future required field on
# KeystoneSpec must be added below AND verified against every fixture.
DATABASE_HOST_ONLY = """\
    host: db.example.com
    port: 3306
    database: keystone
    secretRef:
      name: keystone-db
"""

DATABASE_BOTH_MODES = """\
    clusterRef:
      name: openstack-db
    host: db.example.com
    port: 3306
    database: keystone
    secretRef:
      name: keystone-db
"""

# Same brownfield host mode as DATABASE_HOST_ONLY but with the database NAME
# changed from "keystone" to "renamed". Used by the update-rejection fixture
# that exercises the database-name immutability transition rule: only the name
# differs from the base CR, so the clusterRef/host mode rule stays satisfied.
DATABASE_HOST_RENAMED = """\
    host: db.example.com
    port: 3306
    database: renamed
    secretRef:
      name: keystone-db
"""

# Managed clusterRef mode (no host) with the same database NAME as the base CR.
# Used by the update-rejection fixture that exercises the database-mode
# immutability transition rule: flipping the base brownfield host mode to managed
# clusterRef mode is rejected.
DATABASE_CLUSTERREF_ONLY = """\
    clusterRef:
      name: openstack-db
    database: keystone
    secretRef:
      name: keystone-db
"""

CACHE_SERVERS_ONLY = """\
    backend: dogpile.cache.pymemcache
    servers:
    - "mc:11211"
"""

CACHE_BOTH_MODES = """\
    clusterRef:
      name: openstack-memcached
    backend: dogpile.cache.pymemcache
    servers:
    - "mc:11211"
"""

BOOTSTRAP = """\
  bootstrap:
    adminUser: admin
    adminPasswordSecretRef:
      name: keystone-admin
    region: RegionOne
"""

# Same as BOOTSTRAP but with adminUser changed from "admin" to "root". Used by
# the update-rejection fixture exercising the bootstrap.adminUser immutability
# transition rule.
BOOTSTRAP_RENAMED_ADMIN = """\
  bootstrap:
    adminUser: root
    adminPasswordSecretRef:
      name: keystone-admin
    region: RegionOne
"""

# Same as BOOTSTRAP but with region changed from "RegionOne" to "RegionTwo".
# Used by the update-rejection fixture exercising the bootstrap.region
# immutability transition rule.
BOOTSTRAP_RENAMED_REGION = """\
  bootstrap:
    adminUser: admin
    adminPasswordSecretRef:
      name: keystone-admin
    region: RegionTwo
"""

# Default image block used by every fixture whose rejection is unrelated to the
# image fields. Parameterized (rather than inlined in render) so the
# validation-marker fixtures can mutate just the image to exercise the
# ImageSpec MinLength/Pattern markers.
IMAGE_DEFAULT = """\
    repository: ghcr.io/c5c3/keystone
    tag: "2025.2"
"""

# Image with an empty tag — rejected by the ImageSpec.Tag Pattern marker
# (an empty string does not match the tag grammar).
IMAGE_EMPTY_TAG = """\
    repository: ghcr.io/c5c3/keystone
    tag: ""
"""

# Image that sets BOTH a tag and a digest — rejected by the ImageSpec
# tag/digest XOR XValidation rule (exactly one must be set).
IMAGE_TAG_AND_DIGEST = """\
    repository: ghcr.io/c5c3/keystone
    tag: "2025.2"
    digest: sha256:1111111111111111111111111111111111111111111111111111111111111111
"""

# Database whose name uses a character outside the MySQL identifier set
# (the hyphen) — rejected by the DatabaseSpec.Database Pattern marker.
DATABASE_INVALID_NAME = """\
    host: db.example.com
    port: 3306
    database: keystone-prod
    secretRef:
      name: keystone-db
"""

# Database whose secretRef.name is empty — rejected by the shared
# SecretRefSpec.Name MinLength=1 marker.
DATABASE_EMPTY_SECRETREF_NAME = """\
    host: db.example.com
    port: 3306
    database: keystone
    secretRef:
      name: ""
"""

# Bootstrap whose publicEndpoint is not an HTTP(S) URL — rejected by the
# BootstrapSpec.PublicEndpoint Pattern marker.
BOOTSTRAP_BAD_PUBLIC_ENDPOINT = """\
  bootstrap:
    adminUser: admin
    adminPasswordSecretRef:
      name: keystone-admin
    region: RegionOne
    publicEndpoint: not-a-url
"""


@dataclass(frozen=True)
class Fixture:
    """One invalid-CR fixture: filename + per-fixture overrides."""

    filename: str
    name: str
    comment: str
    replicas: int = 3
    # deployment_extra holds additional spec.deployment sub-fields (4-space
    # indented) emitted inside the deployment block after replicas.
    deployment_extra: str | None = None
    image: str = IMAGE_DEFAULT
    database: str = DATABASE_HOST_ONLY
    cache: str = CACHE_SERVERS_ONLY
    fernet_max_active_keys: int = 3
    credential_keys: str | None = None
    bootstrap: str = BOOTSTRAP
    trailing: str | None = None


def render(fixture: Fixture) -> str:
    """Render a single invalid-CR fixture from the canonical scaffold."""
    parts: list[str] = [
        LICENSE_HEADER,
        fixture.comment.rstrip() + "\n",
        "apiVersion: keystone.openstack.c5c3.io/v1alpha1\n",
        "kind: Keystone\n",
        "metadata:\n",
        f"  name: {fixture.name}\n",
        "spec:\n",
        "  deployment:\n",
        f"    replicas: {fixture.replicas}\n",
    ]
    if fixture.deployment_extra is not None:
        parts.append(fixture.deployment_extra)
    parts += [
        "  image:\n",
        fixture.image,
        "  database:\n",
        fixture.database,
        "  cache:\n",
        fixture.cache,
        "  fernet:\n",
        '    rotationSchedule: "0 0 * * 0"\n',
        f"    maxActiveKeys: {fixture.fernet_max_active_keys}\n",
    ]
    if fixture.credential_keys is not None:
        parts.append(fixture.credential_keys)
    parts.append(fixture.bootstrap)
    if fixture.trailing is not None:
        parts.append(fixture.trailing)
    return "".join(parts)


FIXTURES: list[Fixture] = [
    Fixture(
        filename="02-database-both-modes.yaml",
        name="invalid-database-both-modes",
        database=DATABASE_BOTH_MODES,
        comment="""\
# Keystone CR that sets BOTH spec.database.clusterRef AND
# spec.database.host. Mutual-exclusivity is enforced by the CEL XValidation
# rule on the shared commonv1.DatabaseSpec (types.go) and by defense-in-depth
# in the validating webhook (keystone_webhook.go). Admission must reject
# this CR with an $error referencing spec.database and the message
# "exactly one of clusterRef or host must be set".""",
    ),
    Fixture(
        filename="03-cache-both-modes.yaml",
        name="invalid-cache-both-modes",
        cache=CACHE_BOTH_MODES,
        comment="""\
# Keystone CR that sets BOTH spec.cache.clusterRef AND
# a non-empty spec.cache.servers list. Mutual-exclusivity is enforced by
# the CEL XValidation rule on the shared commonv1.CacheSpec (types.go) and
# by the validating webhook (keystone_webhook.go). Admission must reject
# this CR with an $error referencing spec.cache and the message
# "exactly one of clusterRef or servers must be set". A non-empty servers
# list is required for the CEL guard `size(self.servers) > 0` to fire.""",
    ),
    Fixture(
        filename="04-autoscaling-no-target.yaml",
        name="invalid-autoscaling-no-target",
        trailing="""\
  autoscaling:
    maxReplicas: 10
""",
        comment="""\
# Keystone CR with spec.autoscaling configured but
# neither targetCPUUtilization nor targetMemoryUtilization set. The
# requirement is enforced by the CEL XValidation rule on AutoscalingSpec
# (keystone_types.go) and by the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing spec.autoscaling
# and the message "at least one of targetCPUUtilization or
# targetMemoryUtilization must be set".""",
    ),
    Fixture(
        filename="05-policy-overrides-no-source.yaml",
        name="invalid-policy-overrides-no-source",
        trailing="  policyOverrides: {}\n",
        comment="""\
# Keystone CR with spec.policyOverrides set to an empty
# object — neither rules nor configMapRef populated. The constraint is
# enforced by the CEL XValidation rule on KeystoneSpec.PolicyOverrides
# (keystone_types.go) and by the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing
# spec.policyOverrides and the message "at least one of rules or
# configMapRef must be set".""",
    ),
    Fixture(
        filename="06-policy-overrides-empty-rule-key.yaml",
        name="invalid-policy-overrides-empty-rule-key",
        trailing="""\
  policyOverrides:
    rules:
      '': "role:admin"
""",
        comment="""\
# Keystone CR with spec.policyOverrides.rules containing
# an empty-string map key. Forbidden by the CEL XValidation rule on
# commonv1.PolicySpec (`self.rules.all(k, size(k) > 0)` in types.go) and by
# policy.ValidatePolicyRules in the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing the parent
# fieldPath spec.policyOverrides and the message "policy rule name must
# not be empty". The chainsaw assertion intentionally matches the parent
# path (spec.policyOverrides) — not the deeper spec.policyOverrides.rules
# — because CEL XValidation runs before the validating webhook in the
# admission pipeline and emits the error at the field where the rule is
# declared (here: policyOverrides). The validating webhook's deeper-path
# message is unreachable when the CEL layer rejects first. The empty key
# is quoted ('') so the YAML parser preserves it.""",
    ),
    Fixture(
        filename="07-networkpolicy-empty-ingress.yaml",
        name="invalid-networkpolicy-empty-ingress",
        trailing="""\
  networkPolicy:
    ingress: []
""",
        comment="""\
# Keystone CR with spec.networkPolicy set but
# spec.networkPolicy.ingress as an empty array. The constraint is enforced
# by the CEL XValidation rule on NetworkPolicySpec (keystone_types.go) and
# by the validating webhook (keystone_webhook.go). Admission must reject
# this CR with an $error referencing the parent fieldPath spec.networkPolicy
# and the message "at least one ingress source must be specified". The
# chainsaw assertion intentionally matches the parent path
# (spec.networkPolicy) — not the deeper spec.networkPolicy.ingress —
# because the CEL XValidation rule is declared on the NetworkPolicySpec
# type at the field used as spec.networkPolicy, so the apiserver emits the
# error at that parent path. The validating webhook's deeper-path message
# is unreachable when the CEL layer rejects first.""",
    ),
    Fixture(
        filename="09-replicas-negative.yaml",
        name="invalid-replicas-negative",
        replicas=-1,
        comment="""\
# Keystone CR with spec.deployment.replicas: -1. The
# +kubebuilder:validation:Minimum=1 marker on DeploymentSpec.Replicas
# (keystone_types.go) is a structural CRD check that runs before any
# defaulting path could coerce a negative value. The defaulting webhook
# only normalizes Replicas == 0 (keystone_webhook.go), so -1 reaches the
# Minimum=1 schema layer. Admission must reject this CR with an $error
# referencing the substring "replicas".""",
    ),
    Fixture(
        filename="10-hpa-min-greater-than-max.yaml",
        name="invalid-hpa-min-greater-than-max",
        trailing="""\
  autoscaling:
    minReplicas: 10
    maxReplicas: 5
    targetCPUUtilization: 80
""",
        comment="""\
# Keystone CR with spec.autoscaling.minReplicas greater
# than spec.autoscaling.maxReplicas. The validating webhook
# (keystone_webhook.go) rejects the cross-field combination because an HPA
# rendered with min > max would itself be rejected by the API server.
# Admission must reject this CR with an $error referencing
# spec.autoscaling.minReplicas and the message "must not exceed
# maxReplicas". A targetCPUUtilization is set so the rejection is
# attributable solely to the min/max ordering, not the no-target rule.""",
    ),
    Fixture(
        filename="11-fernet-maxactivekeys-below-minimum.yaml",
        name="invalid-fernet-maxactivekeys-below-minimum",
        fernet_max_active_keys=2,
        comment="""\
# Keystone CR with spec.fernet.maxActiveKeys: 2 — below
# the documented minimum. Enforced by the +kubebuilder:validation:Minimum=3
# marker on FernetSpec.MaxActiveKeys (keystone_types.go) and by
# defense-in-depth in the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing the substring
# "maxActiveKeys". Either layer's message ("should be greater than or
# equal to 3" from CRD schema, "maxActiveKeys must be at least 3" from
# webhook) satisfies the assertion — see plan on layer-order
# tolerance.""",
    ),
    Fixture(
        filename="12-credentialkeys-maxactivekeys-below-minimum.yaml",
        name="invalid-credentialkeys-maxactivekeys-below-minimum",
        credential_keys="""\
  credentialKeys:
    rotationSchedule: "0 0 * * 0"
    maxActiveKeys: 2
""",
        comment="""\
# Keystone CR with spec.credentialKeys.maxActiveKeys: 2 —
# below the documented minimum. Enforced by the
# +kubebuilder:validation:Minimum=3 marker on
# CredentialKeysSpec.MaxActiveKeys (keystone_types.go) and by
# defense-in-depth in the validating webhook (keystone_webhook.go).
# Admission must reject this CR with an $error referencing the substring
# "maxActiveKeys". Either layer's message satisfies the assertion — see
# plan on layer-order tolerance.""",
    ),
    Fixture(
        filename="13-policy-overrides-empty-rule-value.yaml",
        name="invalid-policy-overrides-empty-rule-value",
        trailing="""\
  policyOverrides:
    rules:
      "identity:get_user": ""
""",
        comment="""\
# Keystone CR with spec.policyOverrides.rules containing a
# rule whose VALUE is the empty string. This closes the validation gap the
# 2026-06 audit reported (issue #479): empty rule values previously passed
# admission and reached oslo.policy. Forbidden by the CEL XValidation rule on
# commonv1.PolicySpec (`self.rules.all(k, self.rules[k] != '')` in types.go)
# and by policy.ValidatePolicyRules in the validating webhook
# (keystone_webhook.go). Admission must reject this CR with an $error
# referencing the parent fieldPath spec.policyOverrides and the message
# "policy rule value must not be empty". As with the empty-key sibling
# (06-policy-overrides-empty-rule-key.yaml), the chainsaw assertion matches the parent path
# (spec.policyOverrides) because the CEL XValidation, embedded on the
# policyOverrides field via its PolicySpec type, runs before the validating
# webhook and emits the error at that field. The key is quoted to keep its
# embedded colon unambiguous to the YAML parser.""",
    ),
    # ── Update-rejection fixtures (#466) ────────────────────────────────
    # Unlike the create-rejection fixtures above (each applied once and rejected
    # at admission), these four share name "immutable-fields" with the base CR
    # below so the chainsaw suite applies the base successfully, then applies each
    # variant as an UPDATE that the CRD CEL transition rules (self == oldSelf,
    # evaluated only on UPDATE) reject. The base is brownfield (host mode), so the
    # operator creates no MariaDB CRs and pushes no OpenBao secrets; its finalizer
    # cleanup is a no-op and the ephemeral namespace tears down cleanly.
    Fixture(
        filename="13-immutable-base.yaml",
        name="immutable-fields",
        comment="""\
# Valid base Keystone CR for the field-immutability update-rejection
# fixtures (#466). It is applied FIRST and must SUCCEED. The variants
# 14-17 reuse this name so each is applied as an UPDATE of this object,
# exercising the CRD CEL transition rules on spec.database.database, the
# database mode (clusterRef vs host), spec.bootstrap.adminUser, and
# spec.bootstrap.region.""",
    ),
    Fixture(
        filename="14-immutable-database-name.yaml",
        name="immutable-fields",
        database=DATABASE_HOST_RENAMED,
        comment="""\
# Update of the immutable-fields base CR that renames
# spec.database.database from "keystone" to "renamed". The CEL transition
# rule on KeystoneSpec.Database (self.database == oldSelf.database,
# keystone_types.go) rejects the change on UPDATE. Only the name differs
# from the base, so the clusterRef/host mode rule stays satisfied.
# Admission must reject this UPDATE with an $error referencing the
# substrings "database" and "immutable".""",
    ),
    Fixture(
        filename="15-immutable-database-mode.yaml",
        name="immutable-fields",
        database=DATABASE_CLUSTERREF_ONLY,
        comment="""\
# Update of the immutable-fields base CR that flips spec.database from
# brownfield host mode to managed clusterRef mode. The CEL transition
# rule on KeystoneSpec.Database (has(self.clusterRef) ==
# has(oldSelf.clusterRef), keystone_types.go) rejects the mode change on
# UPDATE. Admission must reject this UPDATE with an $error referencing the
# substrings "database mode" and "immutable".""",
    ),
    Fixture(
        filename="16-immutable-adminuser.yaml",
        name="immutable-fields",
        bootstrap=BOOTSTRAP_RENAMED_ADMIN,
        comment="""\
# Update of the immutable-fields base CR that changes
# spec.bootstrap.adminUser from "admin" to "root". The CEL transition rule
# on BootstrapSpec.AdminUser (self == oldSelf, keystone_types.go) rejects
# the change on UPDATE. Admission must reject this UPDATE with an $error
# referencing the substrings "adminUser" and "immutable".""",
    ),
    Fixture(
        filename="17-immutable-region.yaml",
        name="immutable-fields",
        bootstrap=BOOTSTRAP_RENAMED_REGION,
        comment="""\
# Update of the immutable-fields base CR that changes
# spec.bootstrap.region from "RegionOne" to "RegionTwo". The CEL transition
# rule on BootstrapSpec.Region (self == oldSelf, keystone_types.go) rejects
# the change on UPDATE. Admission must reject this UPDATE with an $error
# referencing the substrings "region" and "immutable".""",
    ),
    Fixture(
        filename="13-image-empty-tag.yaml",
        name="invalid-image-empty-tag",
        image=IMAGE_EMPTY_TAG,
        comment="""\
# Validation-marker wave: Keystone CR with an empty spec.image.tag. The shared
# ImageSpec.Tag is optional but carries a Pattern marker, so an explicit empty
# tag does not match the tag grammar and is rejected by the CRD schema.
# Admission must reject this CR with an $error referencing the substring
# "image.tag".""",
    ),
    Fixture(
        filename="14-database-name-invalid-char.yaml",
        name="invalid-database-name-char",
        database=DATABASE_INVALID_NAME,
        comment="""\
# Validation-marker wave: Keystone CR whose spec.database.database uses a
# hyphen, outside the MySQL identifier character set. Rejected by the
# DatabaseSpec.Database Pattern marker (^[A-Za-z0-9_]+$). Admission must
# reject this CR with an $error referencing the substring "database".""",
    ),
    Fixture(
        filename="15-database-secretref-empty-name.yaml",
        name="invalid-database-secretref-empty-name",
        database=DATABASE_EMPTY_SECRETREF_NAME,
        comment="""\
# Validation-marker wave: Keystone CR whose spec.database.secretRef.name is
# empty. The shared SecretRefSpec.Name now carries MinLength=1, so an empty
# Secret name (previously admitted by "required") is rejected at the CRD
# schema layer. Admission must reject this CR with an $error referencing the
# substring "secretRef".""",
    ),
    Fixture(
        filename="16-middleware-bad-position.yaml",
        name="invalid-middleware-position",
        trailing="""\
  middleware:
  - name: audit
    filterFactory: audit:filter_factory
    position: sideways
""",
        comment="""\
# Validation-marker wave: Keystone CR with a spec.middleware[].position
# value outside the documented enum. The shared PipelinePosition type now
# carries +kubebuilder:validation:Enum=before;after, so "sideways" — which
# would corrupt the api-paste.ini pipeline — is rejected at the CRD schema
# layer. Admission must reject this CR with an $error referencing the
# substring "position".""",
    ),
    Fixture(
        filename="17-uwsgi-keepalive-timeout-conflict.yaml",
        name="invalid-uwsgi-keepalive-timeout",
        trailing="""\
  uwsgi:
    httpKeepAlive: false
    httpKeepAliveTimeout: 30
""",
        comment="""\
# Validation-marker wave: Keystone CR that sets spec.uwsgi.httpKeepAliveTimeout
# while spec.uwsgi.httpKeepAlive is false. The cross-field CEL XValidation
# rule on UWSGISpec (and the validating webhook) reject the combination
# because the --http-keepalive-timeout flag is never emitted without
# keep-alive. Admission must reject this CR with an $error referencing the
# substring "httpKeepAliveTimeout". This raw-YAML fixture is the primary
# coverage for the rule: a typed Go client drops httpKeepAlive: false via
# omitempty before the schema default re-adds it.""",
    ),
    Fixture(
        filename="18-prestop-not-less-than-grace.yaml",
        name="invalid-prestop-grace-window",
        deployment_extra="""\
    preStopSleepSeconds: 20
    terminationGracePeriodSeconds: 15
""",
        comment="""\
# Validation-marker wave: Keystone CR with spec.deployment.preStopSleepSeconds
# (20) not strictly less than spec.deployment.terminationGracePeriodSeconds (15).
# The drain-window CEL XValidation rule on DeploymentSpec (and the validating
# webhook) require a non-zero drain window. Admission must reject this CR with an
# $error referencing the substring "preStopSleepSeconds".""",
    ),
    Fixture(
        filename="19-publicendpoint-not-url.yaml",
        name="invalid-publicendpoint-not-url",
        bootstrap=BOOTSTRAP_BAD_PUBLIC_ENDPOINT,
        comment="""\
# Validation-marker wave: Keystone CR whose spec.bootstrap.publicEndpoint is
# not an HTTP(S) URL. The BootstrapSpec.PublicEndpoint Pattern marker
# (^https?://) now rejects it unconditionally (previously the webhook only
# checked the URL when spec.gateway was set). Admission must reject this CR
# with an $error referencing the substring "publicEndpoint".""",
    ),
    Fixture(
        filename="20-perloggerlevels-invalid-value.yaml",
        name="invalid-perloggerlevels-value",
        trailing="""\
  logging:
    perLoggerLevels:
      sqlalchemy.engine: BOGUS
""",
        comment="""\
# Validation-marker wave: Keystone CR with a spec.logging.perLoggerLevels
# value outside DEBUG/INFO/WARNING/ERROR/CRITICAL. The map-value CEL
# XValidation rule on LoggingSpec.PerLoggerLevels (and the validating
# webhook) reject it; a plain enum on additionalProperties is not
# expressible in CRD v1. Admission must reject this CR with an $error
# referencing the substring "perLoggerLevels".""",
    ),
    Fixture(
        filename="21-image-tag-and-digest.yaml",
        name="invalid-image-tag-and-digest",
        image=IMAGE_TAG_AND_DIGEST,
        comment="""\
# Validation-marker wave: Keystone CR whose spec.image sets BOTH tag and digest.
# The shared ImageSpec carries an XValidation rule requiring exactly one of tag
# or digest, so setting both is rejected by the CRD schema (and mirrored by the
# validating webhook). Admission must reject this CR with an $error referencing
# the substring "digest".""",
    ),
]


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    here = Path(__file__).resolve().parent
    drift: list[str] = []
    for fixture in FIXTURES:
        rendered = render(fixture)
        target = here / fixture.filename
        # (I-001): pin encoding=utf-8 so the em-dash characters in the
        # rendered comments round-trip deterministically on runners with a
        # non-UTF-8 locale; otherwise locale.getpreferredencoding() could
        # mis-decode the on-disk file and falsely flag every fixture as drifted.
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            continue
        if check_only:
            drift.append(fixture.filename)
        else:
            target.write_text(rendered, encoding="utf-8")
            print(f"wrote {fixture.filename}")
    # (W-002): orphan sweep. Without this, removing a Fixture entry
    # without `git rm`'ing the YAML leaves dead code on disk that --check
    # cannot see (it only iterates FIXTURES). Report orphans as drift in
    # check mode; delete them otherwise so the on-disk set matches FIXTURES.
    # Files in _PRE_CC0094_FIXTURES are exempted because they predate
    # and are not generated here.
    expected = {f.filename for f in FIXTURES} | _PRE_CC0094_FIXTURES
    for path in sorted(here.iterdir()):
        if (
            path.is_file()
            and _FIXTURE_FILENAME_PATTERN.match(path.name)
            and path.name not in expected
        ):
            if check_only:
                drift.append(f"{path.name} (orphan: not in FIXTURES)")
            else:
                path.unlink()
                print(f"removed orphan {path.name}")
    if check_only and drift:
        print(
            "drift detected — re-run `python3 _generate.py` to refresh:",
            file=sys.stderr,
        )
        for filename in drift:
            print(f"  {filename}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
