// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package controller

import (
	"context"
	"fmt"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/c5c3/forge/internal/common/conditions"
	"github.com/c5c3/forge/internal/common/database"
	keystonev1alpha1 "github.com/c5c3/forge/operators/keystone/api/v1alpha1"
)

// mariaDBResourceKey returns the client.ObjectKey used for the MariaDB
// Database, User, and Grant CRs owned by keystone. Keeping the naming
// convention (keystone.Name, keystone.Namespace) in one place ensures that the
// provisioning builders, the finalizer cleanup, and the live-resource sentinel
// never disagree on the key — a future name suffix or namespace override
// changes here and propagates to every call site.
func mariaDBResourceKey(keystone *keystonev1alpha1.Keystone) client.ObjectKey {
	return client.ObjectKey{Name: keystone.Name, Namespace: keystone.Namespace}
}

// Condition reason constants for DatabaseReady set on the expand-migrate-
// contract upgrade path (kept keystone-private; the steady-state reasons live in
// internal/common/database as database.Reason*). Dynamic reasons generated by
// setUpgradePhaseRunning (phase+"InProgress") and setUpgradeJobFailed
// (phase+"Failed") are intentionally not extracted here because they are
// parameterised by the upgrade phase name.
const (
	conditionReasonUpgradeTargetChanged  = "UpgradeTargetChanged"
	conditionReasonVersionParseError     = "VersionParseError"
	conditionReasonDowngradeNotSupported = "DowngradeNotSupported"
	conditionReasonUpgradePathInvalid    = "UpgradePathInvalid"
	conditionReasonExpandInProgress      = "ExpandInProgress"
	conditionReasonExpandFailed          = "ExpandFailed"
	conditionReasonMigrateInProgress     = "MigrateInProgress"
	conditionReasonMigrateFailed         = "MigrateFailed"
	conditionReasonUpgradeRollingUpdate  = "UpgradeRollingUpdate"
	conditionReasonContractFailed        = "ContractFailed"
	conditionReasonUpgradeInitiated      = "UpgradeInitiated"
	conditionReasonExpandComplete        = "ExpandComplete"
	conditionReasonMigrateComplete       = "MigrateComplete"
	conditionReasonUpgradeComplete       = "UpgradeComplete"
	conditionReasonUpgradeAborted        = "UpgradeAborted"
)

// upgradeJobSuffixes lists the buildDBJob nameSuffixes for the Jobs created
// during the expand-migrate-contract upgrade flow. abortUpgrade deletes exactly
// these (and not db-sync or schema-check, which belong to the steady-state path)
// so reverting an in-flight upgrade leaves no stale phase Jobs behind (#468).
var upgradeJobSuffixes = []string{"db-expand", "db-migrate", "db-contract"}

// reconcileDatabase ensures the Keystone database schema is provisioned and
// migrated. In managed mode (ClusterRef set) it creates MariaDB Database, User,
// and Grant CRs and waits for them to become Ready before running the db_sync
// Job. In brownfield mode (Host set) it skips the MariaDB CRs and runs db_sync
// directly. The provisioning and steady-state sync flows are shared
// (internal/common/database); the expand-migrate-contract upgrade branch between
// them is keystone-private.
func (r *KeystoneReconciler) reconcileDatabase(ctx context.Context, keystone *keystonev1alpha1.Keystone, configMapName, domainsSecretName string) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	// Managed/brownfield provisioning: MariaDB cluster gate, Database/User/Grant
	// ensure, Dynamic-credentials skip of the User/Grant. A non-zero result means
	// the flow set a not-ready condition and we must return it unchanged.
	res, err := database.ReconcileProvision(ctx, database.ProvisionFlowParams{
		Client:        r.Client,
		Scheme:        r.Scheme,
		Owner:         keystone,
		InstanceName:  keystone.Name,
		Namespace:     keystone.Namespace,
		Database:      &keystone.Spec.Database,
		Conditions:    &keystone.Status.Conditions,
		Generation:    keystone.Generation,
		ConditionType: "DatabaseReady",
		RequeueAfter:  RequeueDatabaseWait,
	})
	if err != nil || !res.IsZero() {
		return res, err
	}

	// Active upgrade: delegate to phase-specific handling.
	if keystone.Status.UpgradePhase != "" {
		// Abort path: reverting spec.image.tag back to the installed release
		// cancels the in-flight upgrade and unblocks a stuck or permanently
		// failed expand/migrate phase (#468). Checked before the
		// target-changed guard below because a revert also satisfies
		// tag != targetRelease and would otherwise return a hard error.
		if keystone.Spec.Image.Tag == keystone.Status.InstalledRelease {
			return r.abortUpgrade(ctx, keystone)
		}
		// Detect tag change during an active upgrade.
		if keystone.Spec.Image.Tag != keystone.Status.TargetRelease {
			logger.Info("Image tag changed during active upgrade",
				"targetRelease", keystone.Status.TargetRelease,
				"newTag", keystone.Spec.Image.Tag,
				"phase", keystone.Status.UpgradePhase)
			conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
				Type:               "DatabaseReady",
				Status:             metav1.ConditionFalse,
				ObservedGeneration: keystone.Generation,
				Reason:             conditionReasonUpgradeTargetChanged,
				Message: fmt.Sprintf("Image tag changed to %s during active upgrade %s → %s; complete or roll back the current upgrade first",
					keystone.Spec.Image.Tag, keystone.Status.InstalledRelease, keystone.Status.TargetRelease),
			})
			r.Recorder.Eventf(keystone, corev1.EventTypeWarning, conditionReasonUpgradeTargetChanged, "Image tag changed to %s during active upgrade %s → %s", keystone.Spec.Image.Tag, keystone.Status.InstalledRelease, keystone.Status.TargetRelease)
			return ctrl.Result{}, fmt.Errorf("image tag changed during active upgrade: current upgrade targets %s but spec.image.tag is %s",
				keystone.Status.TargetRelease, keystone.Spec.Image.Tag)
		}
		return r.reconcileUpgrade(ctx, keystone, configMapName, domainsSecretName)
	}

	// Detect upgrade.
	if isUpgrade(keystone) {
		return r.initiateUpgrade(ctx, keystone)
	}

	// Non-upgrade path: db_sync then schema-check, with terminal metrics emitted
	// per phase and the installed release tracked on success.
	return database.ReconcileSyncJobs(ctx, database.SyncFlowParams{
		Client:   r.Client,
		Scheme:   r.Scheme,
		Recorder: r.Recorder,
		Owner:    keystone,
		Jobs:     keystoneJobSetParams(keystone, configMapName, domainsSecretName),
		RecordTerminal: func(jobSuffix string, observed *batchv1.Job) {
			r.recordDBJobTerminalState(ctx, keystone, jobSuffix, observed)
		},
		Conditions:       &keystone.Status.Conditions,
		Generation:       keystone.Generation,
		ConditionType:    "DatabaseReady",
		RequeueAfter:     RequeueDatabaseWait,
		InstalledRelease: &keystone.Status.InstalledRelease,
		ImageTag:         keystone.Spec.Image.Tag,
	})
}

// abortUpgrade cancels an in-flight upgrade when spec.image.tag is reverted to
// status.installedRelease. It deletes the expand/migrate/contract Jobs, clears
// status.upgradePhase/targetRelease, emits an UpgradeAborted event, and requeues
// so the steady-state db_sync path takes over and re-derives DatabaseReady on
// the next pass. This is the only escape from an upgrade wedged on a stuck or
// permanently failed expand/migrate Job (#468).
//
// Aborting is only safe before the contract phase has run. Expand and migrate
// are additive by design: they create the new columns/tables and backfill data
// without dropping anything the installed release still reads, so the
// pre-contract schema is a superset both releases run against. Contract drops
// the now-unused columns; once it has started, the installed release would be
// pointed at a schema missing fields it expects, so a post-contract revert is
// not a safe rollback. The reverted release is the operator's responsibility to
// validate. The controller does not gate the abort on the current phase.
func (r *KeystoneReconciler) abortUpgrade(ctx context.Context, keystone *keystonev1alpha1.Keystone) (ctrl.Result, error) {
	logger := log.FromContext(ctx)
	abortedTarget := keystone.Status.TargetRelease
	abortedPhase := keystone.Status.UpgradePhase

	// Delete the phase Jobs before clearing status so a transient delete error
	// leaves the upgrade state intact and the next reconcile retries the abort
	// rather than dropping into the steady-state path with orphaned Jobs (#468).
	if err := r.deleteUpgradeJobs(ctx, keystone); err != nil {
		return ctrl.Result{}, fmt.Errorf("deleting upgrade jobs during abort: %w", err)
	}

	keystone.Status.UpgradePhase = ""
	keystone.Status.TargetRelease = ""

	logger.Info("Upgrade aborted: spec.image.tag reverted to installed release",
		"installedRelease", keystone.Status.InstalledRelease,
		"abortedTarget", abortedTarget,
		"abortedPhase", abortedPhase)
	r.Recorder.Eventf(keystone, corev1.EventTypeNormal, conditionReasonUpgradeAborted,
		"Upgrade %s → %s aborted: spec.image.tag reverted to installed release %s",
		keystone.Status.InstalledRelease, abortedTarget, keystone.Status.InstalledRelease)
	return ctrl.Result{Requeue: true}, nil
}

// deleteUpgradeJobs deletes the expand/migrate/contract Jobs owned by keystone.
// NotFound is tolerated so the call is idempotent across requeues, and
// Background propagation removes each Job's owned Pods too rather than orphaning
// them (#468).
func (r *KeystoneReconciler) deleteUpgradeJobs(ctx context.Context, keystone *keystonev1alpha1.Keystone) error {
	logger := log.FromContext(ctx)
	for _, suffix := range upgradeJobSuffixes {
		jobName := fmt.Sprintf("%s-%s", keystone.Name, suffix)
		j := &batchv1.Job{
			ObjectMeta: metav1.ObjectMeta{
				Name:      jobName,
				Namespace: keystone.Namespace,
			},
		}
		err := r.Delete(ctx, j, client.PropagationPolicy(metav1.DeletePropagationBackground))
		switch {
		case apierrors.IsNotFound(err):
			logger.V(1).Info("upgrade phase job already absent during abort", "job", jobName)
		case err != nil:
			return fmt.Errorf("deleting %s: %w", jobName, err)
		default:
			logger.V(1).Info("deleted upgrade phase job during abort", "job", jobName)
		}
	}
	return nil
}

// finalizeDatabaseResources issues Delete for the MariaDB Database, User, and
// Grant CRs named after the Keystone CR, delegating to the shared
// database.FinalizeResources. It returns as soon as the Delete requests have
// been accepted (or tolerated as NotFound) so the Keystone CR finalizer can be
// released in the same reconcile pass; see database.FinalizeResources for the
// deadlock-avoidance rationale.
func (r *KeystoneReconciler) finalizeDatabaseResources(ctx context.Context, keystone *keystonev1alpha1.Keystone) error {
	return database.FinalizeResources(ctx, r.Client, mariaDBResourceKey(keystone))
}
