// SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package controller

import (
	"context"
	"fmt"

	mariadbv1alpha1 "github.com/mariadb-operator/mariadb-operator/api/v1alpha1"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/c5c3/forge/internal/common/conditions"
	"github.com/c5c3/forge/internal/common/database"
	"github.com/c5c3/forge/internal/common/job"
	keystonev1alpha1 "github.com/c5c3/forge/operators/keystone/api/v1alpha1"
)

// mariaDBResourceCtors is the single source of truth for the set of MariaDB CR
// kinds owned by a Keystone CR. Both the finalizer cleanup
// (finalizeDatabaseResources) and the FinalizingDatabase sentinel
// (hasLiveMariaDBResources) iterate over this list, so adding a new kind (e.g.
// Backup) only requires appending one entry here — the cleanup and the
// sentinel then stay in lockstep. Each ctor returns a zeroed pointer suitable
// for Get/Delete; callers set Name and Namespace via mariaDBResourceKey
var mariaDBResourceCtors = []func() client.Object{
	func() client.Object { return &mariadbv1alpha1.Database{} },
	func() client.Object { return &mariadbv1alpha1.User{} },
	func() client.Object { return &mariadbv1alpha1.Grant{} },
}

// mariaDBResourceKey returns the client.ObjectKey used for the MariaDB
// Database, User, and Grant CRs owned by keystone. Keeping the naming
// convention (keystone.Name, keystone.Namespace) in one place ensures that
// buildDatabase, buildUser, buildGrant, hasLiveMariaDBResources, and
// finalizeDatabaseResources never disagree on the key — a future name suffix
// or namespace override changes here and propagates to every call site
func mariaDBResourceKey(keystone *keystonev1alpha1.Keystone) client.ObjectKey {
	return client.ObjectKey{Name: keystone.Name, Namespace: keystone.Namespace}
}

// Condition reason constants for DatabaseReady.
// Dynamic reasons generated by setUpgradePhaseRunning (phase+"InProgress") and
// setUpgradeJobFailed (phase+"Failed") are intentionally not extracted here
// because they are parameterised by the upgrade phase name.
const (
	conditionReasonClusterNotReady       = "ClusterNotReady"
	conditionReasonWaitingForDatabase    = "WaitingForDatabase"
	conditionReasonUpgradeTargetChanged  = "UpgradeTargetChanged"
	conditionReasonDBSyncFailed          = "DBSyncFailed"
	conditionReasonDBSyncInProgress      = "DBSyncInProgress"
	conditionReasonSchemaDriftDetected   = "SchemaDriftDetected"
	conditionReasonSchemaCheckInProgress = "SchemaCheckInProgress"
	conditionReasonDatabaseSynced        = "DatabaseSynced"
	conditionReasonVersionParseError     = "VersionParseError"
	conditionReasonDowngradeNotSupported = "DowngradeNotSupported"
	conditionReasonUpgradePathInvalid    = "UpgradePathInvalid"
	conditionReasonExpandInProgress      = "ExpandInProgress"
	conditionReasonExpandFailed          = "ExpandFailed"
	conditionReasonMigrateInProgress     = "MigrateInProgress"
	conditionReasonMigrateFailed         = "MigrateFailed"
	conditionReasonUpgradeRollingUpdate  = "UpgradeRollingUpdate"
	conditionReasonContractFailed        = "ContractFailed"
	conditionReasonUpgradeInitiated      = "UpgradeInitiated"
	conditionReasonExpandComplete        = "ExpandComplete"
	conditionReasonMigrateComplete       = "MigrateComplete"
	conditionReasonUpgradeComplete       = "UpgradeComplete"
	conditionReasonUpgradeAborted        = "UpgradeAborted"
)

// upgradeJobSuffixes lists the buildDBJob nameSuffixes for the Jobs created
// during the expand-migrate-contract upgrade flow. abortUpgrade deletes exactly
// these (and not db-sync or schema-check, which belong to the steady-state path)
// so reverting an in-flight upgrade leaves no stale phase Jobs behind (#468).
var upgradeJobSuffixes = []string{"db-expand", "db-migrate", "db-contract"}

// isMariaDBClusterReady returns whether the MariaDB cluster referenced by
// spec.database.clusterRef currently reports a Ready=True condition. It
// returns (false, nil) when the cluster CR does not yet exist or is not
// ready, and surfaces transient errors so the reconciler can retry. Keeping
// this check in reconcileDatabase ensures the operator reflects upstream
// database outages in DatabaseReady rather than caching the last sync result
// forever.
func isMariaDBClusterReady(ctx context.Context, c client.Client, keystone *keystonev1alpha1.Keystone) (bool, error) {
	cluster := &mariadbv1alpha1.MariaDB{}
	key := client.ObjectKey{
		Namespace: keystone.Namespace,
		Name:      keystone.Spec.Database.ClusterRef.Name,
	}
	if err := c.Get(ctx, key, cluster); err != nil {
		if apierrors.IsNotFound(err) {
			return false, nil
		}
		return false, fmt.Errorf("getting MariaDB %s: %w", key, err)
	}
	return conditions.IsReady(cluster.Status.Conditions), nil
}

// reconcileDatabase ensures the Keystone database schema is provisioned and
// migrated. In managed mode (ClusterRef set) it creates MariaDB Database, User,
// and Grant CRs and waits for them to become Ready before running the db_sync
// Job. In brownfield mode (Host set) it skips the MariaDB CRs and runs db_sync
// directly.
func (r *KeystoneReconciler) reconcileDatabase(ctx context.Context, keystone *keystonev1alpha1.Keystone, configMapName string) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	// Managed mode: verify MariaDB cluster health, create MariaDB CRs and
	// wait for readiness.
	if keystone.Spec.Database.ClusterRef != nil {
		clusterReady, err := isMariaDBClusterReady(ctx, r.Client, keystone)
		if err != nil {
			return ctrl.Result{}, fmt.Errorf("checking MariaDB cluster readiness: %w", err)
		}
		if !clusterReady {
			logger.Info("MariaDB cluster not ready, requeuing",
				"cluster", keystone.Spec.Database.ClusterRef.Name)
			conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
				Type:               "DatabaseReady",
				Status:             metav1.ConditionFalse,
				ObservedGeneration: keystone.Generation,
				Reason:             conditionReasonClusterNotReady,
				Message: fmt.Sprintf("MariaDB cluster %q is not ready",
					keystone.Spec.Database.ClusterRef.Name),
			})
			return ctrl.Result{RequeueAfter: RequeueDatabaseWait}, nil
		}

		dbReady, err := database.EnsureDatabase(ctx, r.Client, r.Scheme, keystone, buildDatabase(keystone))
		if err != nil {
			return ctrl.Result{}, fmt.Errorf("ensuring Database: %w", err)
		}
		if !dbReady {
			logger.Info("MariaDB Database not ready, requeuing")
			conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
				Type:               "DatabaseReady",
				Status:             metav1.ConditionFalse,
				ObservedGeneration: keystone.Generation,
				Reason:             conditionReasonWaitingForDatabase,
				Message:            "MariaDB Database CR is not ready",
			})
			return ctrl.Result{RequeueAfter: RequeueDatabaseWait}, nil
		}

		userReady, err := database.EnsureDatabaseUser(ctx, r.Client, r.Scheme, keystone, buildUser(keystone), buildGrant(keystone))
		if err != nil {
			return ctrl.Result{}, fmt.Errorf("ensuring database user: %w", err)
		}
		if !userReady {
			logger.Info("MariaDB User/Grant not ready, requeuing")
			conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
				Type:               "DatabaseReady",
				Status:             metav1.ConditionFalse,
				ObservedGeneration: keystone.Generation,
				Reason:             conditionReasonWaitingForDatabase,
				Message:            "MariaDB User or Grant CR is not ready",
			})
			return ctrl.Result{RequeueAfter: RequeueDatabaseWait}, nil
		}
	}

	// Active upgrade: delegate to phase-specific handling.
	if keystone.Status.UpgradePhase != "" {
		// Abort path: reverting spec.image.tag back to the installed release
		// cancels the in-flight upgrade and unblocks a stuck or permanently
		// failed expand/migrate phase (#468). Checked before the
		// target-changed guard below because a revert also satisfies
		// tag != targetRelease and would otherwise return a hard error.
		if keystone.Spec.Image.Tag == keystone.Status.InstalledRelease {
			return r.abortUpgrade(ctx, keystone)
		}
		// Detect tag change during an active upgrade.
		if keystone.Spec.Image.Tag != keystone.Status.TargetRelease {
			logger.Info("Image tag changed during active upgrade",
				"targetRelease", keystone.Status.TargetRelease,
				"newTag", keystone.Spec.Image.Tag,
				"phase", keystone.Status.UpgradePhase)
			conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
				Type:               "DatabaseReady",
				Status:             metav1.ConditionFalse,
				ObservedGeneration: keystone.Generation,
				Reason:             conditionReasonUpgradeTargetChanged,
				Message: fmt.Sprintf("Image tag changed to %s during active upgrade %s \u2192 %s; complete or roll back the current upgrade first",
					keystone.Spec.Image.Tag, keystone.Status.InstalledRelease, keystone.Status.TargetRelease),
			})
			r.Recorder.Eventf(keystone, corev1.EventTypeWarning, conditionReasonUpgradeTargetChanged, "Image tag changed to %s during active upgrade %s \u2192 %s", keystone.Spec.Image.Tag, keystone.Status.InstalledRelease, keystone.Status.TargetRelease)
			return ctrl.Result{}, fmt.Errorf("image tag changed during active upgrade: current upgrade targets %s but spec.image.tag is %s",
				keystone.Status.TargetRelease, keystone.Spec.Image.Tag)
		}
		return r.reconcileUpgrade(ctx, keystone, configMapName)
	}

	// Detect upgrade.
	if isUpgrade(keystone) {
		return r.initiateUpgrade(ctx, keystone)
	}

	// Non-upgrade path: simple db_sync.
	done, err := job.RunJob(ctx, r.Client, r.Scheme, keystone, buildDBSyncJob(keystone, configMapName))
	// Emit db_sync metrics on the terminal-transition observation path
	// regardless of (done, err). In-progress Jobs are no-ops; the per-phase
	// UID annotation on the Keystone CR guarantees at-most-once emission per
	// Job UID.
	r.recordDBJobTerminalState(ctx, keystone, "db-sync")
	if err != nil {
		conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
			Type:               "DatabaseReady",
			Status:             metav1.ConditionFalse,
			ObservedGeneration: keystone.Generation,
			Reason:             conditionReasonDBSyncFailed,
			Message:            fmt.Sprintf("db_sync job failed: %v", err),
		})
		r.Recorder.Eventf(keystone, corev1.EventTypeWarning, conditionReasonDBSyncFailed, "db_sync job failed: %v", err)
		return ctrl.Result{}, fmt.Errorf("running db_sync: %w", err)
	}
	if !done {
		logger.Info("db_sync job in progress, requeuing")
		conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
			Type:               "DatabaseReady",
			Status:             metav1.ConditionFalse,
			ObservedGeneration: keystone.Generation,
			Reason:             conditionReasonDBSyncInProgress,
			Message:            "db_sync job is running",
		})
		return ctrl.Result{RequeueAfter: RequeueDatabaseWait}, nil
	}

	// Schema drift detection after db_sync.
	done, err = job.RunJob(ctx, r.Client, r.Scheme, keystone, buildSchemaCheckJob(keystone, configMapName))
	// Same terminal-transition emission rule as db_sync above: the metric
	// must contribute samples for every DB-related Job so dashboards/alerts
	// observe schema-check failures.
	r.recordDBJobTerminalState(ctx, keystone, "schema-check")
	if err != nil {
		conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
			Type:               "DatabaseReady",
			Status:             metav1.ConditionFalse,
			ObservedGeneration: keystone.Generation,
			Reason:             conditionReasonSchemaDriftDetected,
			Message:            fmt.Sprintf("schema-check job failed: %v", err),
		})
		r.Recorder.Eventf(keystone, corev1.EventTypeWarning, conditionReasonSchemaDriftDetected, "schema-check job failed: %v", err)
		return ctrl.Result{}, fmt.Errorf("running schema-check: %w", err)
	}
	if !done {
		logger.Info("schema-check job in progress, requeuing")
		conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
			Type:               "DatabaseReady",
			Status:             metav1.ConditionFalse,
			ObservedGeneration: keystone.Generation,
			Reason:             conditionReasonSchemaCheckInProgress,
			Message:            "schema-check job is running",
		})
		return ctrl.Result{RequeueAfter: RequeueDatabaseWait}, nil
	}

	// Track installed release after successful db_sync and schema check
	keystone.Status.InstalledRelease = keystone.Spec.Image.Tag

	conditions.SetCondition(&keystone.Status.Conditions, metav1.Condition{
		Type:               "DatabaseReady",
		Status:             metav1.ConditionTrue,
		ObservedGeneration: keystone.Generation,
		Reason:             conditionReasonDatabaseSynced,
		Message:            "Database schema is up to date (revision verified)",
	})
	r.Recorder.Event(keystone, corev1.EventTypeNormal, conditionReasonDatabaseSynced, "Database schema is up to date")
	return ctrl.Result{}, nil
}

// abortUpgrade cancels an in-flight upgrade when spec.image.tag is reverted to
// status.installedRelease. It deletes the expand/migrate/contract Jobs, clears
// status.upgradePhase/targetRelease, emits an UpgradeAborted event, and requeues
// so the steady-state db_sync path takes over and re-derives DatabaseReady on
// the next pass. This is the only escape from an upgrade wedged on a stuck or
// permanently failed expand/migrate Job (#468).
//
// Aborting is only safe before the contract phase has run. Expand and migrate
// are additive by design: they create the new columns/tables and backfill data
// without dropping anything the installed release still reads, so the
// pre-contract schema is a superset both releases run against. Contract drops
// the now-unused columns; once it has started, the installed release would be
// pointed at a schema missing fields it expects, so a post-contract revert is
// not a safe rollback. The reverted release is the operator's responsibility to
// validate. The controller does not gate the abort on the current phase.
func (r *KeystoneReconciler) abortUpgrade(ctx context.Context, keystone *keystonev1alpha1.Keystone) (ctrl.Result, error) {
	logger := log.FromContext(ctx)
	abortedTarget := keystone.Status.TargetRelease
	abortedPhase := keystone.Status.UpgradePhase

	// Delete the phase Jobs before clearing status so a transient delete error
	// leaves the upgrade state intact and the next reconcile retries the abort
	// rather than dropping into the steady-state path with orphaned Jobs (#468).
	if err := r.deleteUpgradeJobs(ctx, keystone); err != nil {
		return ctrl.Result{}, fmt.Errorf("deleting upgrade jobs during abort: %w", err)
	}

	keystone.Status.UpgradePhase = ""
	keystone.Status.TargetRelease = ""

	logger.Info("Upgrade aborted: spec.image.tag reverted to installed release",
		"installedRelease", keystone.Status.InstalledRelease,
		"abortedTarget", abortedTarget,
		"abortedPhase", abortedPhase)
	r.Recorder.Eventf(keystone, corev1.EventTypeNormal, conditionReasonUpgradeAborted,
		"Upgrade %s \u2192 %s aborted: spec.image.tag reverted to installed release %s",
		keystone.Status.InstalledRelease, abortedTarget, keystone.Status.InstalledRelease)
	return ctrl.Result{Requeue: true}, nil
}

// deleteUpgradeJobs deletes the expand/migrate/contract Jobs owned by keystone.
// NotFound is tolerated so the call is idempotent across requeues, and
// Background propagation removes each Job's owned Pods too rather than orphaning
// them (#468).
func (r *KeystoneReconciler) deleteUpgradeJobs(ctx context.Context, keystone *keystonev1alpha1.Keystone) error {
	logger := log.FromContext(ctx)
	for _, suffix := range upgradeJobSuffixes {
		jobName := fmt.Sprintf("%s-%s", keystone.Name, suffix)
		j := &batchv1.Job{
			ObjectMeta: metav1.ObjectMeta{
				Name:      jobName,
				Namespace: keystone.Namespace,
			},
		}
		err := r.Delete(ctx, j, client.PropagationPolicy(metav1.DeletePropagationBackground))
		switch {
		case apierrors.IsNotFound(err):
			logger.V(1).Info("upgrade phase job already absent during abort", "job", jobName)
		case err != nil:
			return fmt.Errorf("deleting %s: %w", jobName, err)
		default:
			logger.V(1).Info("deleted upgrade phase job during abort", "job", jobName)
		}
	}
	return nil
}

// finalizeDatabaseResources issues Delete for the MariaDB Database, User, and
// Grant CRs named after the Keystone CR. It returns as soon as the Delete
// requests have been accepted (or tolerated as NotFound) so the Keystone CR
// finalizer can be released in the same reconcile pass.
//
// The function intentionally does not block on the MariaDB operator completing
// its own teardown. Waiting for the CRs to disappear from etcd created a
// deadlock under concurrent deletions: as long as the Keystone finalizer held
// the CR in etcd, Kubernetes garbage collection could not cascade-delete the
// owned Deployment, so the keystone Pod kept its connections open, so the
// MariaDB operator could not DROP DATABASE, so the Database CR stayed
// Terminating — and the finalizer never released. Releasing immediately breaks
// that cycle: GC cascade-deletes the Pod, connections close, and the MariaDB
// operator completes the drop asynchronously. Owner references set by
// reconcileDatabase guarantee the CRs are still cleaned up even if the explicit
// Delete below is a no-op.
//
// NotFound responses from Delete are treated as success so repeat invocations
// (operator restart, external deletion, prior completed cleanup) are
// idempotent. Brownfield CRs (Host-only, no ClusterRef) flow through the same
// path: every Delete is a no-op NotFound.
func (r *KeystoneReconciler) finalizeDatabaseResources(ctx context.Context, keystone *keystonev1alpha1.Keystone) error {
	logger := log.FromContext(ctx).WithValues(
		"keystone", client.ObjectKeyFromObject(keystone),
	)
	key := mariaDBResourceKey(keystone)

	for _, ctor := range mariaDBResourceCtors {
		obj := ctor()
		obj.SetName(key.Name)
		obj.SetNamespace(key.Namespace)
		err := r.Delete(ctx, obj)
		if apierrors.IsNotFound(err) {
			logger.V(1).Info("MariaDB resource already absent, skipping delete",
				"resource", fmt.Sprintf("%T", obj))
			continue
		}
		if err != nil {
			return fmt.Errorf("deleting %T %s: %w", obj, key, err)
		}
	}

	return nil
}
