{{- include "operator-library.webhookConfiguration" (dict
      "root" .
      "mutatingWebhookName" "mcontrolplane.kb.io"
      "validatingWebhookName" "vcontrolplane.kb.io"
      "mutatePath" "/mutate-c5c3-io-v1alpha1-controlplane"
      "validatePath" "/validate-c5c3-io-v1alpha1-controlplane"
      "apiGroup" "c5c3.io"
      "resource" "controlplanes") }}
