# SPDX-FileCopyrightText: Copyright 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: external-secrets
      version: ">=0.10.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    webhook:
      port: 9443
    certController:
      enabled: true
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
