{{- include "operator-library.webhookConfiguration" (dict
      "root" .
      "mutatingWebhookName" "mkeystone.kb.io"
      "validatingWebhookName" "vkeystone.kb.io"
      "mutatePath" "/mutate-keystone-openstack-c5c3-io-v1alpha1-keystone"
      "validatePath" "/validate-keystone-openstack-c5c3-io-v1alpha1-keystone"
      "apiGroup" "keystone.openstack.c5c3.io"
      "resource" "keystones") }}
